### ISSUE TITLE
Cannot Run the Template with Nested Files

### ISSUE THREAD

**Issue by OnurGurdogan** [DanySK/Template-LaTeX-CI#62]
Hi,

First of all I need to say thank you I guess.. Because it saved a lot time of me. 

I was using the template without a problem since today. When I tried to import some other .tex files where are located under different folders but under the same repository, I got an error missing `\begin{document}` inside the sub latex files. It is true that I have not used `\begin{document}` inside the sub latex files but this is the rule from latex, right? I tested my setup locally and it is worked fine.

I do not know why I am getting this error but maybe you can help..

Best regards,

From log:

```
Persons/gurdoganOnur/test.tex:22: Missing \begin{document}.
```

**Comment by DanySK** [comment]
Closing as fixed, reopen if needed
